### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by gesker** [melloware/quarkus-faces#138]
No dynamic resource handler registered for: qr. Do you miss a dependency? issued on display of QR code at http://localhost:8080/ui/multimedia/barcode.xhtml

**Comment by melloware** [comment]
oh whoops i bet i missed something let me debug it.

**Comment by melloware** [comment]
Thanks for reporting!  I fixed it.

**Comment by gesker** [comment]
You bet, @melloware!

BTW, thank you for pushing this repo out to the world. I've been building a new application using Primefaces and Quarkus and the web.xml and pom.xml in this project made for excellent reference material. 

Any other kind of feedback you're looking for? I'd be happy to send anything I see your way

**Comment by melloware** [comment]
That is great to hear!  Just let me know if you find any other quarkus tidbits in your work you think should be added to this showcase for others. Also feel free to check out and update our Wiki page on this that has some tidbits and gotchas with Quarkus.
