### ISSUE TITLE
Jakarta EE10/MyFaces 4

### ISSUE THREAD

**Issue by gesker** [melloware/quarkus-faces#151]
Just curious if you had plans to bump from 2.3-next to 4 on this project?

I noticed that [MyFaces 4 RC1](https://search.maven.org/artifact/org.apache.myfaces.core/myfaces-api/4.0.0-RC1/jar) was published to the maven repos but I would think that https://github.com/quarkusio/quarkus/issues/21574 will remain a blocker. Beyond that issue opened 21-November I hadn't read anything else about the plans at Quarkus regarding[ Jakarta EE](https://github.com/jakartaee/jakarta.ee); [Faces](https://github.com/jakartaee/faces) in particular. 

Also, do you anticipate that the myfaces-quarkus extension will flip out of experimental status before or after that namespace/upgrade from javax to jakarta? Best guess?

**Comment by melloware** [comment]
These are great questions.

Quarkus control is out of my hands so when quarkus updates from javax to Jakarta specs is anybody guess

Once that happens then MyFaces quarkus extension can be updated for Jakarta. And then finally this demo would be updated. 

However the Quarkus project isn't really concerned about EE specs or Faces. It's thanks to the amazing team at MyFaces that it even has support.   But I will say that I personally think it's an impressive way to deploy a container JSF app!

**Comment by gesker** [comment]
I agree.  JSF fits very well.

My current project still has a way to go but developing on Quarkus using JSF has been pleasant. Actually, it was a little rough to start. THEN I found this/your repository. I would certainly say that anyone looking to use Quarkus and build the front with JSF should have no real issue... just stop here first. :)

Smooth sailing ever since. So, thank you, Sir!

**Comment by melloware** [comment]
agreed!  Glad to see my project here was useful to some people!

**Comment by melloware** [comment]
@gesker also I just released OmniFaces on the official Quarkiverse so you may want to stop using that AdminFaces plugin and use:

```xml
<dependency>
            <groupId>io.quarkiverse.omnifaces</groupId>
            <artifactId>quarkus-omnifaces</artifactId>
            <version>3.0.0</version>
        </dependency>
```

https://github.com/quarkiverse/quarkus-omnifaces

**Comment by anumber8** [comment]
> 

I've been following your work and its impressive. And as I love everything JSF and Quarkus,  i did implement a huge project now going to production. Although I did implement using AdminFaces, I will give a try on your omnifaces.

**Comment by melloware** [comment]
you may get an EL Expression error if you do just add this and I fixing in 3.0.1 release.

```xml
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.el</artifactId>
            <version>4.0.2</version>
        </dependency>
```

**Comment by melloware** [comment]
See: https://github.com/apache/myfaces/pull/458

**Comment by gesker** [comment]
https://quarkus.io/blog/road-to-quarkus-3/

Figured I'd add this here just in case you didn't see it @melloware. I did ask on that post about Faces coming over from the Jakarta project, too, along with the name space change.

**Comment by melloware** [comment]
Yep I have a prototype working with MyFaces 4 and OmniFaces 4.  I have been fixing a few bugs and reported a couple to Quarkus.

**Comment by melloware** [comment]
Linked to: https://github.com/quarkiverse/quarkus-primefaces/issues/16

**Comment by melloware** [comment]
This one is next on my list.

**Comment by melloware** [comment]
@gesker all committed!   I have not tried GraalVM Native mode yet but at leats JVM is working on Myfaces 4.0.0 Quarkus 3.

**Comment by melloware** [comment]
Opened a couple of MyFaces tickets. Also was reported Hot swap deployment is not working in Dev mode and I confirmed that as well as broken.
