### ISSUE TITLE
Native Image Deployment

### ISSUE THREAD

**Issue by melloware** [melloware/quarkus-faces#157]
Working on getting this project to work with Native GraalVM deployment but ran into one issue.

Reported: https://github.com/graalvm/mandrel/issues/411

**Comment by melloware** [comment]
I am getting really close to having this working.  A few more issues to work out!

**Comment by melloware** [comment]
Just a preview teaser... I loaded the same exact page _(datatable crud.xhtml)_ on the same machine _(my laptop)_ and captured the results using `p:lifecycle`.  The results are....**stunning**.

## Jetty 9.4.50.v20221201, MyFaces 2.3-next, JDK 17.0.5:
**Page Load:**
![image](https://user-images.githubusercontent.com/4399574/221419383-154832f0-3a5a-445b-9d1c-a28d95c85342.png)

**AJAX Submit:**
![image](https://user-images.githubusercontent.com/4399574/221419668-08bf1769-2565-4660-a1f0-c67c92e34cbc.png)




## Mandrel GraalVM 22.3, Quarkus 2.16.3, MyFaces 2.3-next, JDK 17.0.5:
**Page Load:**
![image](https://user-images.githubusercontent.com/4399574/221419569-6718a649-6a1f-480a-be7f-23a843201853.png)

**AJAX Submit:**
![image](https://user-images.githubusercontent.com/4399574/221419603-c82abee7-6319-47d3-9a12-f307bea04836.png)

**Comment by gesker** [comment]
Wow!
Can. Not. Wait.
Thank you so much @melloware !

**Comment by melloware** [comment]
If any of you want to test it out just check out this latest code and run.

```
mvn -Pnative
docker run -i --rm -p 8081:8081 melloware/quarkus-faces:12.0.0
```
