### ISSUE TITLE
Quarkus and Premium Primefaces templates

### ISSUE THREAD

**Issue by ancgate** [melloware/quarkus-faces#176]
Hi Mello, 
Thanks for doing this. This is really helpful. Can I integrate this project with Primefaces premium templates?

**Comment by melloware** [comment]
yep i know someone who has already done this with the Babylon premium template.

**Comment by ancgate** [comment]
Thank you very much! is there any pain points that I should be aware of?

**Comment by melloware** [comment]
cc @tmulle as he is the one doing it right now.

**Comment by ancgate** [comment]
Thanks @melloware. @tmulle, any way you can get help me with that? I would like to understand your process.

**Comment by melloware** [comment]
@ancgate so far there are no gotchas that I know if its just implementing a premium template like you would in any normal PF app.

**Comment by zeppelinux** [comment]
I'm trying to use Freya with quarkus-faces. Have one issue with template layout css not loading, [here](https://forum.primefaces.org/viewtopic.php?f=141&t=78176&sid=a2f8d6b4a9206cc26f072f6d3a08e6bb) is some more info. Everything else look sgood!

**Comment by melloware** [comment]
@zeppelinux a few notes:

1. Looking in Quarkus Faces showcase for flags.css I see a resource declared like this `background:url("\#{resource['showcase:css/flags/flags_responsive.png']}"` so make sure you resources are in the correct location and the resources URL is pointing at the correct place.

2. As for your template.xhtml not loading make sure all URL's are corrected in it and compare with my showcase template.xhtml.

I have Babylon Theme working fine with Quarkus Faces so I know Freya will work you are just missing some tweaks probably

**Comment by zeppelinux** [comment]
@melloware I followed your advise and it is resolved. Thanks!
