### ISSUE TITLE
PhotoCam errror

### ISSUE THREAD

**Issue by zeppelinux** [melloware/quarkus-faces#215]
Noticed that /ui/multimedia/photocam/photoCam.xhtml generates error: "Webcam.js caught an error: No supported webcam interface found."
Same functionality works in PF official demo.

**Comment by melloware** [comment]
I will take a look.

**Comment by melloware** [comment]
Just tested running `mvn clean compile quarkus:dev` and PhotoCam is working fine for me locally. 

1. What browser are you using?
2. Are you sure you have not disabled your camera? Try it in icognito mode?

**Comment by zeppelinux** [comment]
Confirmed, It works when accessing the app using http://**localhost**:8080/ui/multimedia/photocam/photoCam.xhtml

When I add  quarkus.http.host=0.0.0.0 to the application.properties and access it using IP instead of localhost it doesn't.

**Comment by melloware** [comment]
See the docs: https://primefaces.github.io/primefaces/12_0_0/#/components/photocam?id=browser-compatibility

specifically you are running into the "Browser Compatability" part.  You can't run it like that localhost but it will work for real on your server.

> Navigators like Google Chrome (version 47 and later) require secure origins (HTTPS or LOCALHOST) to activate media devices functionality. Thus, unless you are accessing the page from LOCALHOST, PhotoCam is likely to do not work in a plain HTTP call. More details can be found here: https://developers.google.com/web/updates/2015/10/chrome-47-webrtc
