### ISSUE TITLE
Can't redefine an element inserted in a template

### ISSUE THREAD

**Issue by devramo** [melloware/quarkus-faces#472]
Please find below the needed files to reproduce the issue in a page **test.xhtml**.

Also attached the quarkus-faces project with these files.
[quarkus-faces-main.zip](https://github.com/user-attachments/files/16918685/quarkus-faces-main.zip)
http://localhost:8000/test.xhtml to test the issue describe below:

We should normally see the text: SUCCESS, but instead CONTENT2 is shown.

test.xhtml
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="jakarta.faces.facelets">
<ui:composition template="/t1.xhtml">
	<ui:define name="content2">	
		SUCCESS
	</ui:define>
</ui:composition>
</html>
```

t1.xhtml
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="jakarta.faces.html"
	xmlns:ui="jakarta.faces.facelets"
>
<h:head>
</h:head>
<h:body>
	<ui:insert name="content">
		<ui:include src="/t2.xhtml"/>
	</ui:insert>
</h:body>
</html>
```

t2.xhtml
```
<!DOCTYPE html>
<ui:composition xmlns:ui="jakarta.faces.facelets">
	<ui:insert name="content2">
        CONTENT2
    </ui:insert>
</ui:composition>
```

**Comment by melloware** [comment]
@devramo not quarkus faces related.  See this reproducer:
[quarkus-472.zip](https://github.com/user-attachments/files/16918938/quarkus-472.zip)

Unzip and run `mvn clean jetty:run -Pmojarra40` and go to http://localhost:8080/ you will see "SUCCESS"

Run `mvn clean jetty:run -Pmyfaces40` and go to http://localhost:8080/ you will see "Content2"

So it looks like a core MyFaces 4.0.2 issue which is what Quarkus Faces uses.

**Comment by devramo** [comment]
Many Thanks for your quick and nice response.
This kind of code was always working in our projects using mojarra implementation.

In that case, mojarra is more permissive than myfaces and allow <ui:insert> inside <ui:include>.

Using <ui:decorate> instead of <ui:include> fixed the issue.
https://stackoverflow.com/questions/10778068/what-is-the-real-conceptual-difference-between-uidecorate-and-uiinclude

**Comment by melloware** [comment]
Excellent thanks for posting back!
