### ISSUE TITLE
remove unsupported params in web.xml  ?

### ISSUE THREAD

**Issue by nimo23** [melloware/quarkus-faces#485]
Does the following settings in web.xml have any impact? 

https://github.com/melloware/quarkus-faces/blob/278236a60b076ca7b17c1c47b7d6a3b67f683bef/src/main/resources/META-INF/web.xml#L108

Also the following params:

- org.apache.myfaces.COMPONENT_UNIQUE_IDS_CACHE_SIZE
- jakarta.faces.FACELETS_DEVELOPMENT
- jakarta.faces.FACELETS_SKIP_COMMENT
- jakarta.faces.STATE_SAVING_METHOD

This settings doesn't seem to exist anymore in the current version of myfaces, right? Or do these settings only not work in Quarkus-MyFaces?

**Comment by melloware** [comment]
Nope you can see here it was remove in Faces 4.0+: https://myfaces.apache.org/#/core40

Last version its in is Faces 2.3

**Comment by melloware** [comment]
Thanks its removed now!

**Comment by melloware** [comment]
All the others you mentioned still are valid.

**Comment by melloware** [comment]
when I look at the MYFaces code for looging out variables I see this...

```java
        paramValue = facesContext.getExternalContext().getInitParameter("org.apache.myfaces.COMPONENT_UNIQUE_IDS_CACHE_SIZE");
        if (paramValue == null)
        {
            logMessageToAppropriateLevel("No context init parameter 'org.apache.myfaces.COMPONENT_UNIQUE_IDS_CACHE_SIZE' found, using default value '100'.");
        }
```

It looks like it only logs it if its NOT FOUND
