### ISSUE TITLE
WebSocket example not working

### ISSUE THREAD

**Issue by leandro-costa** [melloware/quarkus-faces#486]
URL: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/ajax/websocket.xhtml

**Comment by melloware** [comment]
Yep i am working on it. See: https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4684

Its actually a Quarkus bug:  https://github.com/quarkusio/quarkus-http/pull/167

**Comment by melloware** [comment]
WebSocket example is now working: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/ajax/websocket.xhtml?jfwid=ca83e
