### ISSUE TITLE
Documentation for each improvement?

### ISSUE THREAD

**Issue by thatsIch** [melloware/quarkus-faces#50]
Greetings!

Did you write down how much each of the noted optimizations improved the results individually?

![image](https://user-images.githubusercontent.com/2210496/125277364-a0673680-e311-11eb-8123-26c72a8e452c.png)

Sincerely

**Comment by melloware** [comment]
@thatsIch No I did not.  I just wanted to show the cumulative tips and tricks I use for JSF apps.  I will say though probably the 2 biggest are the MOVE_SCRIPTS_TO_BOTTOM and the CombinedResourceHandler.

**Comment by thatsIch** [comment]
Thanks for answering. Have a great day!
