### ISSUE TITLE
FormAuth: Getting status 302 when redirecting after login

### ISSUE THREAD

**Issue by muchiri08** [melloware/quarkus-faces#501]
I am having an issue in redirection after login and I seem to not figure out what the issue might be. When I check from the web tools I see the quarkus-redirect-location with the correct url but can't redirect and returns me to the login page. Below is my login impl and configs:

<h5>Login bean</h5>
<pre>
<code>
    @ConfigProperty(name = "quarkus.http.auth.form.cookie-name")
    String cookieName;
    @Inject
    FacesContext facesContext;

    public void authenticate() {
        System.out.println("authenticating");
        try {
            var request = (HttpServletRequest) facesContext.getExternalContext().getRequest();

            switch (generateCookie(request)) {
                case SUCCESS ->
                    facesContext.getExternalContext().redirect("/app/onboard.xhtml");
                case FAILED ->
                    facesContext.addMessage(null,
                            new FacesMessage(FacesMessage.SEVERITY_ERROR, "invalid user credentials", null));
            }
        } catch (IOException | InterruptedException e) {
            throw new RuntimeException("something went wrong during authentication");
        }
    }

    private AuthStatus generateCookie(HttpServletRequest request) throws IOException, InterruptedException {
        System.out.println("Generate Cookie called");
        var securityCheckUrl = request.getRequestURL().toString()
                .replace("/account/login", "/j_security_check");
        var response = jSecurityCheckRequest(securityCheckUrl);
        System.out.println(" STATUS: " + response.statusCode());
        if (response.statusCode() == 401) {
            return AuthStatus.FAILED;
        }

        var fcResponse = (HttpServletResponse) facesContext.getExternalContext().getResponse();
        setCookie(response, fcResponse);
        return AuthStatus.SUCCESS;
    }

    private void setCookie(HttpResponse<String> response, HttpServletResponse fcResponse) {
        System.out.println("in the set cookie");
        var responseMap = response.headers().map();
        if (responseMap.containsKey("set-cookie")) {
            System.out.println("next part set cookie");
            var cookieString = responseMap.get("set-cookie").get(0);
            var quarkusCookie = new Cookie(cookieName, cookieString.split("=")[1]);
            quarkusCookie.setMaxAge(30 * 60); //30 min expiry
            quarkusCookie.setHttpOnly(true);
            fcResponse.addCookie(quarkusCookie);
        }
    }

    private HttpResponse<String> jSecurityCheckRequest(String securityCheckUrl)
            throws IOException, InterruptedException {
        var response = HttpClient.newHttpClient().send(HttpRequest.newBuilder()
                .uri(URI.create(securityCheckUrl))
                .POST(HttpRequest.BodyPublishers.ofString(
                        "j_username=" + username + "&j_password=" + password))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .build(), HttpResponse.BodyHandlers.ofString());
        return response;
    }

    private enum AuthStatus {
        SUCCESS, FAILED;
    }
</code>
</pre>

<h5>Property file</h5>
<pre>
<code>
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password, r.name FROM systemUser u JOIN uRole r ON u.roleId = r.id WHERE u.username=?
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled=true 
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=2 
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=account/login.xhtml
quarkus.http.auth.form.landing-page=
quarkus.http.auth.form.error-page=
</code>
</pre>

<h5>Web xml</h5>

```
    <session-config>
        <cookie-config>
            <http-only>true</http-only>
        </cookie-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>
    <welcome-file-list>
        <welcome-file>index.xhtml</welcome-file>
    </welcome-file-list>

    <!-- Context parameters - Primefaces-->
    <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
    <context-param>
        <param-name>primefaces.COOKIES_SAME_SITE</param-name>
        <param-value>Strict</param-value>
    </context-param>
    <context-param>
        <param-name>primefaces.FLEX</param-name>
        <param-value>true</param-value>
    </context-param>  

    <!-- Context parameters - Omnifaces-->
    <context-param>
        <param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
        <param-value>/*.xhtml</param-value>
    </context-param>
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>Secured</web-resource-name>
            <url-pattern>/app/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <role-name>ADMIN</role-name>
            <role-name>USER</role-name>
        </auth-constraint>
    </security-constraint>
    <security-role>
        <role-name>ADMIN</role-name>
    </security-role>
    <security-role>
        <role-name>USER</role-name>
    </security-role>
```

**Comment by melloware** [comment]
@muchiri08 @Ryaru was having similar issues: https://github.com/melloware/quarkus-faces/issues/409

This week I will try to put together a small Faces Form Auth example.

**Comment by muchiri08** [comment]
@melloware Thank you. 

Also if there could be an example of doing the form auth by implementing the interfaces rather than using the property file to do the login I would appreciate.

**Comment by melloware** [comment]
@muchiri08 i just threw this quick example together.  Run `mvn quarkus:dev` and hit localhost:8080 .  Login with `scott` and `jboss`  as the username/password.
[quarkus-faces-formauth.zip](https://github.com/user-attachments/files/17790618/quarkus-faces-formauth.zip)

This is not a traditional JEE app so you need to do things the Quarkus way...

Don't use `web.xml` for security use Quarkus.  The config below says "secure everything" except JS/CSS and certain XHTML pages which need to be public to be access like login.xhtml and error.xhtml.

```properties
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated
quarkus.http.auth.permission.form.paths=login.xhtml,error.xhtml,viewExpired.xhtml,jakarta.faces.resource/*
quarkus.http.auth.permission.form.policy=permit
quarkus.http.auth.permission.form.auth-mechanism=form
```

**Comment by muchiri08** [comment]
@melloware Sorry I have been away. So the above property file code snippet you have posted works perfect only if on the ui I change my form and post directly to <strong>j_security_check</strong>. When I do the programatic way the authentication returns status 200 which is successfull, then I do the faces context redirection(as shown from the prev post I made on the authenticate() method), on the browser it tries to redirect, then instead, it shows status 302 on the network tab and returns me to the login page.

**Comment by melloware** [comment]
OK so that tells me the redirect that Quarkus VertX doesn't think you are authenticated and re-routes you back to the login page.

**Comment by muchiri08** [comment]
I think so yes.

**Comment by melloware** [comment]
Yep its missing the credential cookie so it thinks you are not authenticated.

**Comment by melloware** [comment]
I think I know why you are setting it in the `Faces Repsonse` but calling `facesContext.getExternalContext().redirect("/app/onboard.xhtml");` and that redirect I am pretty sure is discarding the current response.  I think this would happen in Faces regardless of Quarkus?

**Comment by muchiri08** [comment]
I have just done a quick example on jakarta ee and seems the cookie is committed to the request before redirection. It did work. Test done on mojarra + jakarta ee 10.

```
@Named
@RequestScoped
public class Navigator {

    @Inject
    FacesContext facesContext;

    public void navigate(String page) throws IOException {
        var cookie = new Cookie("my-cookie", "myvalue");
        var response = (HttpServletResponse) facesContext.getExternalContext().getResponse();
        response.addCookie(cookie);
        facesContext.getExternalContext().redirect(page);
    }
}
```

**Comment by melloware** [comment]
I just tested and it works fine.
[quarkus-faces-formauth.zip](https://github.com/user-attachments/files/17804809/quarkus-faces-formauth.zip)

1. Unzip file
2. Run `mvn quarkus:dev`
3. Navigate to http:://localhost:8080
4. Press the "Navigate Cookie" button.
5. Redirected to `error.xhtml` and cookie in Cookie Jar

![image](https://github.com/user-attachments/assets/eec0e362-285b-4454-bd3b-87bbc1f18a5d)

**Comment by muchiri08** [comment]
@melloware  I have written a test app with sign up, login and home page. The sign up page is just to create a user then login with the credentials. The issue I have come across is some credentials gets authenticated successfully and redirection to home page is done. Others get authenticated successfully but redirection fails and the status 302 is shown. For this to be seen I had so signup severally with different users credentials. On my case, one of the failing credentials are when username=admin and password=admin. This might not be a case on your side but it has happened.

[quarkus-faces-formauth.zip](https://github.com/user-attachments/files/17815535/quarkus-faces-formauth.zip)

1. Unzip file
2. Update the db config property file
  ```
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=<db-username>
quarkus.datasource.password=<db-password>
quarkus.datasource.jdbc.url=<db-url>
```

3. Run `mvn quarkus:dev`
4. Navigate to http://localhost:8080

**Comment by melloware** [comment]
OK thanks to @gastaldi found your bug.  Your cookie parsing was wrong.
[qfaces-501.zip](https://github.com/user-attachments/files/17818103/qfaces-501.zip)

correct way to parse the cookie.

```java
var cookieString = responseMap.get("set-cookie").get(0);
io.undertow.server.handlers.Cookie cookie = io.undertow.util.Cookies.parseSetCookieHeader(cookieString);
var quarkusCookie = new Cookie(cookieName, cookie.getValue());
```

**Comment by muchiri08** [comment]
That's so odd. Even username with 5 chars do not work either lol. Should we end the chat at this point?  I think this will work just fine for now.
